### ISSUE TITLE
German animal group name?

### ISSUE THREAD

**Issue by Kirkkt** [Kirkkt/german-qna#1]
One thing I really enjoy about English is animal group names, for example, one can say "a group of lions", which is correct, but one can also say "a pride of lions" to mean the same thing and it sounds awesome. Similarly, an ambush of tigers, a murder of crows, and my all-time favorite - a singular of boars.

Is there something like this in German?

**Comment by JoySR** [comment]
Actually, I've never known the collective nouns for animals both in English and in German. 
But found a pretty relative webpage about this theme: [https://www.reddit.com/r/German/wiki/animalgroups](Groups of animals). This page is in German. Ask me anything if it is difficult to understand.

**Comment by Kirkkt** [comment]
Toll! Exactly what I was looking for. Danke schön!! btw I can access reddit.
