### ISSUE TITLE
第一人称射击游戏问题系列 zu, für, um 表示目的??!!

### ISSUE THREAD

**Issue by Kirkkt** [Kirkkt/german-qna#2]
我看了一个德语版的第一人称射击游戏的视频，注意到：

`Drücken Sie Leertaste für (action name)`
`Drücken Sie F zum Wechseln: (weapon name)`
`Drücken Sie N, um das Nachtsichtgerät auszuschalten.`

这里zu, für, um 都可以表示目的，那怎么知道什么时候用哪个？除了语感之外有没有什么规则的？

**Comment by JoySR** [comment]
这三者的区别和语感关系不大，语法上面就可以区别开来。

für + 四格名词。
zu + 动词 （to do)，或者表示动作或者行为的名词，比如上面的 wechseln。
um (etwas) zu + 动词。etwas 相当于动词的宾语。

以上面的句子为例，其实第二句可以换成：
Drücken Sie F, um (weapon name) zu wechseln。

但是用 zu 这种形式的话，就可以把变量 weapon name 提取出来放到后面了。xD
