### ISSUE TITLE
第一人称射击游戏问题系列 Nähern uns jetzt dem ziel. 为啥不是wir?

### ISSUE THREAD

**Issue by Kirkkt** [Kirkkt/german-qna#3]
我看了一个德语版的第一人称射击游戏的视频，注意到：
`Nähern uns jetzt dem ziel.` - We are approaching the target.

不理解为啥这里用uns， 如果要强调动词的话`Nähern wir jetzt dem ziel.`不就好了

看看下面这个“let's do this”句式，也是一样的结构吧（在我看来）
`Dann gehen wir da hin. `

**Comment by JoySR** [comment]
nähern 是个反身动词，用的时候要加 sich，也就是 sich nähern。
sich 是有人称变化的，在这个句子里是 uns ( wir -> uns），像今天早晨时谈到的 sich freuen，因为表达“我”很期待，所以是 mich (Ich freue mich auf ...)。
关于 sich 的更多内容，可以期待一下周五。xD

这里其实是省略了主语 wir。加上 wir 之后是 Nähern wir uns jetzt dem Ziel. uns 在这里绝对不可以省略。

P.S.：德语名词任何情况下无论放在句子的哪个位置，都必须要首字母大写。
