### ISSUE TITLE
第一人称射击游戏问题系列之 Wie ist ihr Status? 为啥不是 was?

### ISSUE THREAD

**Issue by Kirkkt** [Kirkkt/german-qna#4]
我看了一个德语版的第一人称射击游戏的视频，注意到：
`Wie ist ihr Status?`

不明白这里为啥用wie，我理解wie=how，was=what。
另外，我如果非要用was的话对吗？
网上有人说不用理解，强行记下就好，我想问问你。

**Comment by JoySR** [comment]
如果只是谈谈看法的话，可能是语感的关系，我倒是觉得 wie=how 很符合这里的语境。
“你那边的情况怎么样？” 询问的是一个当前的状态，是好是坏的这种状态。Wir ist deine neue Arbeit? 你的新工作怎么样？
非要用 was 的话也许不能算错吧，但是可能大家都不这么用。

P.S.: 刚刚搜索的时候，搜到了 Wie ist meine IP-Adresse? 的说法，而且如果搜 Was ist meine IP-Adresse? 的话，搜到的也是 Wie ist... 这个就连我也觉得不知道该如何解释呢。
