### ISSUE TITLE
Meiner Meinung nach ist das falsch. 语序疑问

### ISSUE THREAD

**Issue by Kirkkt** [Kirkkt/german-qna#5]
动词在第二位我能理解，但不明白为什么nach要放到meiner Meinung之后，单纯为了强调meiner Meinung吗？

那如果我说 Nach meiner Meinung ist das falsch. 行吗？这样我觉得更顺诶

**Comment by JoySR** [comment]
先放链接，不知道能不能访问，如果访问不了的话我会贴全文：https://de.wikipedia.org/wiki/Postposition

也就是德语有些介词是可以后置的。而像 nach 在表达 meiner Meinung nach 时就是后置的，nach 放到前面行么？语法上不算错，但是 meiner Meinung nach 已经基本相当于一个固定的词组了。如果不是“我”的观点，而是其他人的观点，nach 可前可后，但 meiner Meinung 的话，还是把 nach 放到后面吧。
